### ISSUE TITLE
hunger still makes server stall after extracting it from HUD

### ISSUE THREAD

**Issue by yo-we** [BlockMen/hunger#1]
Placing the code somewhere else did not resolve the problem. As you split the code, I play the game and open a new issue, but we consider this being the same problem as
  https://github.com/BlockMen/hud/issues/17
which actually has been closed, but never resolved.

Here the log of the last server reset:
21:08:47: ACTION[main]: IRC: Disconnected.
[plants_lib] Stand by, playing out the rest of the aircheck mapblock log
(there are 0 entries)...
[plants_lib] Stand by, playing out the rest of the no-aircheck mapblock log
(there are 0 entries)...
21:08:47: ERROR[main]: ServerEnv: Trying to store id=15388 statically but block (-11,0,14) already contains 49 objects. Forcing delete.
21:08:47: ERROR[main]: ServerEnv: Trying to store id=15458 statically but block (-11,0,14) already contains 49 objects. Forcing delete.
21:08:47: ERROR[main]: ServerEnv: Trying to store id=15528 statically but block (-11,0,14) already contains 49 objects. Forcing delete.
21:08:47: ERROR[main]: ServerEnv: Trying to store id=15594 statically but block (-11,0,14) already contains 49 objects. Forcing delete.
21:08:47: ERROR[main]: ServerEnv: Trying to store id=15653 statically but block (-11,0,14) already contains 49 objects. Forcing delete.
21:08:47: ERROR[main]: ServerEnv: Trying to store id=15723 statically but block (-11,0,14) already contains 49 objects. Forcing delete.
21:08:47: ERROR[main]: ServerEnv: Trying to store id=15780 statically but block (-11,0,14) already contains 49 objects. Forcing delete.
21:08:47: ERROR[main]: ServerEnv: Trying to store id=15826 statically but block (-11,0,14) already contains 49 objects. Forcing delete.
21:08:47: ERROR[main]: ServerEnv: Trying to store id=15845 statically but block (-11,0,14) already contains 49 objects. Forcing delete.
21:08:47: ERROR[main]: ServerEnv: Trying to store id=15911 statically but block (-11,0,14) already contains 49 objects. Forcing delete.
21:08:47: ERROR[main]: ERROR: An unhandled exception occurred: /home/minetest/.minetest/mods/hud/api.lua:91: attempt to call method 'hud_change' (a nil value)
21:08:47: ERROR[main]: stack traceback:
21:08:47: ERROR[main]:  /home/minetest/.minetest/mods/hud/api.lua:91: in function 'change_item'
21:08:47: ERROR[main]:  /home/minetest/.minetest/mods/hunger/functions.lua:57: in function 'update_hunger'
21:08:47: ERROR[main]:  /home/minetest/.minetest/mods/hunger/functions.lua:92: in function 'callback'
21:08:47: ERROR[main]:  /opt/minetest-0.4.12/bin/../builtin/game/item.lua:467: in function </opt/minetest-0.4.12/bin/../builtin/game/item.lua:405>
21:08:47: ERROR[main]:  (tail call): ?
21:08:47: ERROR[main]:  /home/minetest/.minetest/mods/pipeworks/wielder.lua:334: in function 'act'
21:08:47: ERROR[main]:  /home/minetest/.minetest/mods/pipeworks/wielder.lua:109: in function 'wielder_on'
21:08:47: ERROR[main]:  /home/minetest/.minetest/mods/pipeworks/wielder.lua:145: in function 'action_on'
21:08:47: ERROR[main]:  ...netest/.minetest/mods/mesecons/mesecons/internal.lua:189: in function '?'
21:08:47: ERROR[main]:  ...est/.minetest/mods/mesecons/mesecons/actionqueue.lua:90: in function 'execute'
21:08:47: ERROR[main]:  ...est/.minetest/mods/mesecons/mesecons/actionqueue.lua:84: in function '?'
21:08:47: ERROR[main]:  ...opt/minetest-0.4.12/bin/../builtin/game/register.lua:341: in function <...opt/minetest-0.4.12/bin/../builtin/game/register.lua:329>

**Comment by BlockMen** [comment]
> As you split the code, I play the game and open a new issue, but we consider this being the same problem as BlockMen/hud#17 which actually has been closed, but never resolved.

If you think this is a game you should understand the rules. As the log shows it is NOT the same issue. The log says, that the mod was not able to call a player specific function (which might be caused by the "fake" player mentioned in the last issue you posted. I will add another check for that today, if it still crashes there might not be much i can do then.
But if you want still "play" this game with me you can post your results later then here...

**Comment by BlockMen** [comment]
Added another check to make sure it is actually a player (but there were already two checks). https://github.com/BlockMen/hud/commit/7ece8b87bec0451f24c2d8e2cffcd06b12a0262b

The problem is that this here

> 21:08:47: ERROR[main]: ERROR: An unhandled exception occurred: /home/minetest/.minetest/mods/hud/api.lua:91: attempt to call method 'hud_change' (a nil value)

can only apprear when there is a problem with calling this minetest API function. So either the given player is not a player (which is checked again now) or the player is somehow corrupted. But that would be an engine issue then

**Comment by yo-we** [comment]
Hello BlockMen,  sorry if I hurt you, that was meant to be understood with humor. Re-reading it, I understand that it was not very well formulated from my side.
I see you re-opened the issue. If you need more traces of what is going on, you can hand me instrumented code to have more information in the log.

**Comment by BlockMen** [comment]
I didn't mean to close, just hit wrong button ;)

Anyway, a feedback if that change helped would be nice.

**Comment by BlockMen** [comment]
Open a new issue if you still have problems.
